export const Products = [
  {
    id: "1",
    name: "This product",
    description: "This is a description for a product 1",
    image: "https://picsum.photos/1000/200",
    quantity: 10,
    price: 20,
  },
  {
    id: "2",
    name: "This product 2",
    description: "This is a description for a product 2",
    image: "https://picsum.photos/200",
    quantity: 20,
    price: 40,
  },
  {
    id: "3",
    name: "This product 3",
    description: "This is a description for a product 3",
    image: "https://picsum.photos/200",
    quantity: 20,
    price: 1000,
  },
  {
    id: "4",
    name: "This product 3",
    description: "This is a description for a product 3",
    image: "https://picsum.photos/200",
    quantity: 20,
    price: 1000,
  },
  {
    id: "5",
    name: "This product 3",
    description: "This is a description for a product 3",
    image: "https://picsum.photos/200",
    quantity: 20,
    price: 1000,
  },
];
